version: "3.9"

services:
    client:
        container_name: prakticum-client-${REPOSITORY_NAME}${SHORT_SHA}
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:80"
            - "443:443"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
          - REPOSITORY_NAME=${REPOSITORY_NAME}
          - SHORT_SHA=${SHORT_SHA}
    server:
        depends_on:
          - postgres
        container_name: prakticum-server-${REPOSITORY_NAME}${SHORT_SHA}
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:443"
        environment:
          SERVER_PORT: ${SERVER_PORT}
          REPOSITORY_NAME: ${REPOSITORY_NAME}
          SHORT_SHA: ${SHORT_SHA}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_PATH: ${POSTGRES_PATH}
    postgres:
      container_name: postgres
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_PATH: ${POSTGRES_PATH}
      volumes:
        - ${POSTGRES_PATH}:/var/lib/postgresql/data


