name: deploy
on:
  push:
  pull_request:
    branches:
      - main
      - ci-cd
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: remove temp dir if exists (temporary solution)
        run: sudo rm -rf /home/runner/actions-runner/_work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/tmp
      - uses: actions/checkout@v3
      - name: set env var for new docker containers postfix
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REPOSITORY_NAME: ${{ github.event.repository.name }}
          envkey_SHORT_SHA: ${{ env.short_sha }}
          envkey_CLIENT_PORT: 80
          envkey_SERVER_PORT: 3001
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          file_name: .env
          fail_on_empty: true
      - name: stopping & removing old containers if exist
        run: docker compose down --remove-orphans || true
      - name: create tmp folder
        run: mkdir -p tmp/pgdata
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap
      - name: building containers & starting it
        run: docker compose up -d --build
