name: deploy
on:
  pull_request:
  push:
    branches: [ ci-cd ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: set env var for new docker containers postfix
        run: echo "short_sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REPOSITORY_NAME: ${{ github.event.repository.name }}
          envkey_SHORT_SHA: ${{ env.short_sha }}
          envkey_CLIENT_PORT: 80
          envkey_SERVER_PORT: 3001
          envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          envkey_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          file_name: .env
          fail_on_empty: true
      - name: stopping & removing old containers if exist
        run: docker compose down --remove-orphans || true
      - name: check for node version
        run: echo "node -v =`echo $(node -v)`"
      - name: check for npm version
        run: echo "npm -v =`echo $(npm -v)`"
      - name: check for yarn version
        run: echo "yarn -v =`echo $(yarn -v)`"
      - name: Install main deps
        run: yarn
      - name: Initialize
        run: yarn lerna bootstrap
      - name: building containers & starting it
        run: docker compose up -d --build
